---
title: "Player Data Prep"
author: "Xavier Genelin"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nflverse)
library(fst)
```


```{r seasons}
start_season <- 2015
```

# Weekly Data

```{r player_weekly}
player_weekly <- load_player_stats(seasons = c(start_season:most_recent_season()), stat_type = "offense") %>%
  filter(season_type == "REG") %>%
  filter(position_group %in% c("QB", "RB", "TE", "WR")) %>%
  mutate(position = ifelse(str_trim(position) == "HB", "RB", position)) %>%
  rename(Player = player_display_name,
         Completions = completions,
         Attempts = attempts,
         `Passing Yds` = passing_yards,
         `Passing TDs` = passing_tds,
         Interceptions = interceptions,
         Sacks = sacks,
         `Sack Yards` = sack_yards,
         `Sack Fum` = sack_fumbles,
         `Sack Fum Lost` = sack_fumbles_lost,
         `Passing Air Yds` = passing_air_yards,
         `Passing YAC` = passing_yards_after_catch,
         `Passing 1st Downs` = passing_first_downs,
         `Passing EPA` = passing_epa,
         `Passing 2pt Conv` = passing_2pt_conversions,
         Carries = carries,
         `Rushing Yds` = rushing_yards,
         `Rushing TDs` = rushing_tds,
         `Rushing Fum` = rushing_fumbles,
         `Rushing Fum Lost` = rushing_fumbles_lost,
         `Rushing 1st Downs` = rushing_first_downs,
         `Rushing EPA` = rushing_epa,
         `Rushing 2pt Conv` = rushing_2pt_conversions,
         Receptions = receptions,
         Targets = targets,
         `Receiving Yds` = receiving_yards,
         `Receiving TDs` = receiving_tds,
         `Receiving Fum` = receiving_fumbles,
         `Receiving Fum Lost` = receiving_fumbles_lost,
         `Receiving Air Yds` = receiving_air_yards,
         `Receiving YAC` = receiving_yards_after_catch,
         `Receiving 1st Downs` = receiving_first_downs,
         `Receiving 2pt Conv` = receiving_2pt_conversions,
         `Target Share` = target_share,
         `Air Yds Share` = air_yards_share,
         `Special Teams TDs` = special_teams_tds,
         `Fantasy Points` = fantasy_points,
         `Fantasy Points PPR` = fantasy_points_ppr) %>%
  mutate(`Target Share` = round(`Target Share`, 4))

player_weekly
```

# Season

```{r player_season}
player_season <- player_weekly %>%
  group_by(player_id, Player, season, position, headshot_url) %>%
  summarise(Completions = sum(Completions),
            Attempts = sum(Attempts),
            `Passing Yds` = sum(`Passing Yds`),
            `Passing TDs` = sum(`Passing TDs`),
            Interceptions = sum(Interceptions),
            Sacks = sum(Sacks),
            `Sack Yds` = sum(`Sack Yards`),
            `Sack Fum` = sum(`Sack Fum`),
            `Sack Fum Lost` = sum(`Sack Fum Lost`),
            `Passing YAC` = sum(`Passing YAC`),
            `Passing 1st Downs` = sum(`Passing 1st Downs`),
            `Passing 2pt Conv` = sum(`Passing 2pt Conv`),
            Carries = sum(Carries),
            `Rushing Yds` = sum(`Rushing Yds`),
            `Rushing TDs` = sum(`Rushing TDs`),
            `Rushing Fum` = sum(`Rushing Fum`),
            `Rushing Fum Lost` = sum(`Rushing Fum Lost`),
            `Rushing 1st Downs` = sum(`Rushing 1st Downs`),
            `Rushing 2pt Conv` = sum(`Rushing 2pt Conv`),
            Receptions = sum(Receptions),
            Targets = sum(Targets),
            `Receiving Yards` = sum(`Receiving Yds`),
            `Receiving TDs` = sum(`Receiving TDs`),
            `Receiving Fum` = sum(`Receiving Fum`),
            `Receiving Fum Lost` = sum(`Receiving Fum Lost`),
            `Receiving Air Yards` = sum(`Receiving Air Yds`),
            `Receiving YAC` = sum(`Receiving YAC`),
            `Receiving 1st Downs` = sum(`Receiving 1st Downs`),
            `Receiving 2pt Conv` = sum(`Receiving 2pt Conv`),
            `Special Teams TDs` = sum(`Special Teams TDs`),
            `Fantasy Points` = sum(`Fantasy Points`),
            `Fantasy Points PPR` = sum(`Fantasy Points PPR`))

player_season
```

# Kicking
```{r player_kicking_weekly}
player_kicking_weekly <- load_player_stats(seasons = start_season:most_recent_season(), stat_type = "kicking") %>%
  filter(season_type == "REG") %>%
  select(-ends_with("_list")) %>%
  mutate_at(vars(fg_made:gwfg_blocked), ~replace_na(., 0)) %>%
  mutate(`Fantasy Points` = (fg_made_0_19 * 3) + (fg_made_20_29 * 3) + (fg_made_30_39 * 3) + (fg_made_40_49 * 4) + (fg_made_50_59 * 5) + (fg_made_60_ * 5) - (fg_missed_0_19 * 2) - (fg_missed_20_29 * 2) - (fg_missed_30_39 * 2) - (fg_missed_40_49 * 1) - (fg_missed_50_59 * 1) - (fg_missed_60_ * 1) + (pat_made *1) - (pat_missed - 1),
         `Fantasy Points PPR` = `Fantasy Points`) %>%
  filter(position == "K") %>%
  rename(`FG Made` = fg_made,
         `FG Att` = fg_att,
         `FG Missed` = fg_missed,
         `FG Blocked` = fg_blocked,
         `FG Long` = fg_long,
         `FG%` = fg_pct,
         `FG Made 0-19` = fg_made_0_19,
         `FG Made 20-29` = fg_made_20_29,
         `FG Made 30-39` = fg_made_30_39,
         `FG Made 40-49` = fg_made_40_49,
         `FG Made 50-59` = fg_made_50_59,
         `FG Made 60+` = fg_made_60_,
         `FG Missed 0-19` = fg_missed_0_19,
         `FG Missed 20-29` = fg_missed_20_29,
         `FG Missed 30-39` = fg_missed_30_39,
         `FG Missed 40-49` = fg_missed_40_49,
         `FG Missed 50-59` = fg_missed_50_59,
         `FG Missed 60+` = fg_missed_60_,
         `PAT Made` = pat_made,
         `PAT Att` = pat_att,
         `PAT Missed` = pat_missed,
         `PAT Blocked` = pat_blocked,
         `PAT%` = pat_pct)
```

```{r player_kicking_season}
player_kicking_season <- player_kicking_weekly %>%
  group_by(season, player_display_name, player_id, position, position_group, team, headshot_url) %>%
  summarise(`FG Made` = sum(`FG Made`, na.rm = TRUE),
            `FG Att` = sum(`FG Att`, na.rm = TRUE),
            `FG Missed` = sum(`FG Missed`, na.rm = TRUE),
            `FG Blocked` = sum(`FG Blocked`, na.rm = TRUE),
            `FG Long` = max(`FG Long`, na.rm = TRUE),
            `FG Made 0-19` = sum(`FG Made 0-19`, na.rm = TRUE),
            `FG Made 20-29` = sum(`FG Made 20-29`, na.rm = TRUE),
            `FG Made 30-39` = sum(`FG Made 30-39`, na.rm = TRUE),
            `FG Made 40-49` = sum(`FG Made 40-49`, na.rm = TRUE),
            `FG Made 50-59` = sum(`FG Made 50-59`, na.rm = TRUE),
            `FG Made 60+` = sum(`FG Made 60+`, na.rm = TRUE),
            `FG Missed 0-19` = sum(`FG Missed 0-19`, na.rm = TRUE),
            `FG Missed 20-29` = sum(`FG Missed 20-29`, na.rm = TRUE),
            `FG Missed 30-39` = sum(`FG Missed 30-39`, na.rm = TRUE),
            `FG Missed 40-49` = sum(`FG Missed 40-49`, na.rm = TRUE),
            `FG Missed 50-59` = sum(`FG Missed 50-59`, na.rm = TRUE),
            `FG Missed 60+` = sum(`FG Missed 60+`, na.rm = TRUE),
            `PAT Made` = sum(`PAT Made`, na.rm = TRUE),
            `PAT Att` = sum(`PAT Att`, na.rm = TRUE),
            `PAT Missed` = sum(`PAT Missed`, na.rm = TRUE),
            `PAT Blocked` = sum(`PAT Blocked`, na.rm = TRUE),
            `Fantasy Points` = sum(`Fantasy Points`, na.rm = TRUE),
            `Fantasy Points PPR` = sum(`Fantasy Points PPR`, na.rm = TRUE))  %>%
  mutate(`FG%` = round(`FG Made` / `FG Att`, 4),
         `PAT%` = round(`PAT Made` / `PAT Att`, 4))
```

```{r combine_datasets}
player_weekly <- bind_rows(player_weekly, player_kicking_weekly) %>%
  mutate(Player = coalesce(Player, player_display_name),
         recent_team = coalesce(recent_team, team)) %>%
  select(-c(player_display_name, team, player_name)) %>%
  filter(position %in% c("QB", "RB", "FB", "WR", "TE", "K"))

player_season <- bind_rows(player_season, player_kicking_season) %>%
  mutate(Player = coalesce(Player, player_display_name)) %>%
  select(-c(player_display_name, team, position_group)) %>%
  filter(position %in% c("QB", "RB", "FB", "WR", "TE", "K"))
```

# Save to fst files
```{r player_fsts}
write.fst(player_season, "./Fantasy-Football-App/data/player_season.fst")
write.fst(player_weekly, "./Fantasy-Football-App/data/player_weekly.fst")
```